services:

  backend:
    # image: nobs_backend
    # image: azure-fastapi-nextjs_backend:latest
    container_name: backend
    build:
      context: ./backend
    restart: always
    env_file:
      - .secret
    tty: true
    ports:
      # host:container
      - 80:80
    volumes:
      - ./backend/website:/website
    working_dir: /website
    command: ["fastapi", "dev" , "main.py", "--host=0.0.0.0", "--port=80", "--reload"]
    environment:
      - LOGFIRE_SEND_TO_LOGFIRE=true
      - LOGFIRE_ENVIRONMENT=LAPTOP
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBREAKPOINT=ipdb.set_trace
      - WEB_APP_ENV=LAPTOP # TEST or PROD
    #dns:
    #  - 8.8.8.8
    #  - 8.8.4.4
